apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-no-gcp
  labels:
    app: hello-world-no-gcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-no-gcp
  template:
    metadata:
      labels:
        app: hello-world-no-gcp
    spec:
      containers:
        - name: hello-world-no-gcp
          image: nginx:1.16.sdfsd
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: hello-world-html-no-gcp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-html-no-gcp
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Hello World</title>
    </head>
    <body>
      <h1>Hello, World!</h1>
      <p>This is a simple HTML app deployed using ArgoCD.</p>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service-no-gcp
spec:
  selector:
    app: hello-world-no-gcp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
